### ISSUE TITLE
Error when Invalid column name included in the keys

### ISSUE THREAD

**Issue by sajohnston** [capitalone/dataCompareR#11]
If an invalid column name is included in the keys, the invalid column name fixes in the data frames creates an issue when the checks are done to see if the keys exist.

A user might not be able to tell what the issue is, as in their version of the data frames, the keys are present, and it's not obvious what the changed column names are after a fix.

**Comment by rnobleeddy** [comment]
Pretty sure we implemented a small change - I know see 

```
> rCompare(pressure, pressure2, keys = "temp rature")
Running rCompare...
Fixing syntactically incorrect keys
    Keys changed from -  temp rature
                   to -  temp.rature
Error in checkKeysExist(df1, keys) : ERROR : Key temp.rature not found
```

**Comment by rnobleeddy** [comment]
@sajohnston I think this is sufficient to point the user in the right direction, but let me know what you think!

**Comment by sajohnston** [comment]
Yeah, this seems like enough for now! Originally, we hadn't communicated the changes, so it wasn't clear what the issue was.

**Comment by rnobleeddy** [comment]
Closing as change now in master (or was before)
