### ISSUE TITLE
Make package available via conda

### ISSUE THREAD

**Issue by hechth** [capitalone/dataCompareR#123]
Hi, I'm planning on using your project for dataframe comparison and it seems really nice! Since we manage all dependencies with [conda](https://docs.anaconda.com/anaconda/packages/r-language-pkg-docs/), would it be possible for you to submit your package also to [conda-forge](https://conda-forge.org/docs/user/introduction.html)?

If you need any help or advice just let me know!

Thank you very much!

**Comment by KrishanBhasin** [comment]
Hi @hechth 

We have an open PR [here](https://github.com/conda-forge/staged-recipes/pull/16037) to onboard `dataCompareR` into `conda-forge`. If you subscribe to that thread you should be able to see as soon as it is uploaded

**Comment by KrishanBhasin** [comment]
Hi @hechth
It should be up now - could you confirm it is all working for you before I close this issue?

**Comment by hechth** [comment]
Looks good and can be installed - thank you very much!
