### ISSUE TITLE
saveReport should have a '...' to pass in summary arguments

### ISSUE THREAD

**Issue by sajohnston** [capitalone/dataCompareR#45]
You can't pass in any of the summary arguments to saveReport at the moment (which calls summary to get the content of the report). It would be good to have this option to have more flexible output.

**Comment by rnobleeddy** [comment]
Fix made and works 

![image](https://user-images.githubusercontent.com/12643616/44262878-8806e900-a214-11e8-8b3d-e6acc3a6efca.png)

Now to add unit tests...

**Comment by rnobleeddy** [comment]
Which highlighted that the unit tests we do have for `saveReport` are a little poor. 

We have lots of tests that check it fails when it should, but no tests that show it works. I'm  not sure I knew that you could call functions to create temporary files when this package was written, so I will try to make improvements!

**Comment by rnobleeddy** [comment]
It also made sense to add an option to show all mismatches in the report. This isn't perfect as the message still calls it a sample

![image](https://user-images.githubusercontent.com/12643616/44266371-3b2a0f00-a222-11e8-8ee4-607c141b5e22.png)


But it''ll do!
