### ISSUE TITLE
Majority of functions missing while installing package : dataCompareR

### ISSUE THREAD

**Issue by ANDEF89** [capitalone/dataCompareR#48]
I am using R version 3.3.2 .
 when i install dataCompareR from CRAN, i get only 3 functions namely :
1. rCompare
2. generateMismatchData
3. saveReport
I need other functions from the package 
I tried installing using
library(devtools)
install_git('https://github.com/capitalone/dataCompareR.git', branch = 'master',
             subdir = 'dataCompareR', type = 'source', repos = NULL)

the package gets installed but when i load it i get this error : 
 library(dataCompareR)
Error in fetch(key) : 
  lazy-load database 'C:/.../Documents/R/win-library/3.3/dataCompareR/help/dataCompareR.rdb' is corrupt

**Comment by rnobleeddy** [comment]
Those are the only functions that the package exports - they're the functions that we expected would be useful to the end users, so I'd be interested to find out more about what you're trying to do.

If you want to make use of the internal functions you can access them via 3 colons in the format

`dataCompareR::functionName`

For example, to use the function `validateData` you can use

`dataCompareR::validateData`

Generally we've written documentation for all the functions, but it might not be quite as clear as the user facing functions. It's also worth pointing out we validate inputs/data up front and not in every function, therefore please take care when using internal functions as they're likely to bypass checks like argument type and validity.

Less sure about the lazy-load problem. I've definitely seen this before on other packages, usually when using `devtools` to install from github. Usually restarting R helps, but if not, let us know.

**Comment by rnobleeddy** [comment]
Closing this for now as it's not clear what's expected - @ANDEF89 if you still have concerns, happy for you to reopen.
