### ISSUE TITLE
Unit tests throw warnings due to testthat changes

### ISSUE THREAD

**Issue by rnobleeddy** [capitalone/dataCompareR#72]
There are now 146 warnings courtesy of

``` 
`is_true()` is deprecated. Please use `expect_true()` instead.
```

See `https://github.com/r-lib/testthat/blob/master/NEWS.md` for more details.

**Comment by ChrisBeeley** [comment]
Is this why the package is no longer on CRAN? Seems like an easy fix, want me to take a look?

**Comment by rnobleeddy** [comment]
Probably the first place to look! I don't work at Capital One anymore so I can't submit a new build to CRAN, but I will check there's nothing else on top of what @Lextuga007 has fixed, and then get it ready so it can be submitted.

**Comment by ChrisBeeley** [comment]
Is the package still being maintained? @Lextuga007 and I are happy to assist because we both love this package :-)

**Comment by sajohnston** [comment]
It is! I'm just the only one maintaining it at the moment, and I haven't had as much time to dedicate to it recently, but that should change soon.

**Comment by sajohnston** [comment]
As mentioned in the PR, I'll be taking a look at this today and hopefully pushing it back up to the CRAN soon.
