### ISSUE TITLE
dplyr warnings about deprecated code 

### ISSUE THREAD

**Issue by sajohnston** [capitalone/dataCompareR#87]
These warnings don't show up every time ('once per session'). Running the tests with R 4.0.0 and dplyr 0.8.5 produced the following below, but not all the tests were run yet, so I will add more as they come up. 

``` r
testCheckPrintObject.R:38: warning: print only generates message when data sets match
select_() is deprecated. 
Please use select() instead

The 'programming' vignette or the tidyeval book can help you
to program with select() : https://tidyeval.tidyverse.org
This warning is displayed once per session.

testCheckPrintObject.R:62: warning: print returns message and data when mismatches occur
arrange_() is deprecated. 
Please use arrange() instead

The 'programming' vignette or the tidyeval book can help you
to program with arrange() : https://tidyeval.tidyverse.org
This warning is displayed once per session.

testCheckPrintObject.R:62: warning: print returns message and data when mismatches occur
funs() is soft deprecated as of dplyr 0.8.0
Please use a list of either functions or lambdas: 

  # Simple named list: 
  list(mean = mean, median = median)

  # Auto named with `tibble::lst()`: 
  tibble::lst(mean, median)

  # Using lambdas
  list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
This warning is displayed once per session.
```

**Comment by ben1787** [comment]
Is this going to be resolved?

**Comment by KrishanBhasin** [comment]
It's on our list but unfortunately we have higher priority work at the moment. Would you be able to opening a PR addressing this, @ben1787? (no obligation, of course)

**Comment by Rey-ND** [comment]
Hi there @KrishanBhasin, 

I assume you and your team are still working on higher priority work at the moment to resolve this? It's on its last warning life cycle.
Out of curiosity what's the 'PR' mean in your mention to Ben1787? 
Open to others creating a pull request and attempting to resolve (if I get time one weekend)?

`lifecycle::last_warnings()
[[1]]
<deprecated>
message: `select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
backtrace:
  1. dataCompareR::rCompare(...)
  2. dataCompareR:::processFlow(...)
  3. dataCompareR:::prepareData(dfa, dfb, keys, trimChars)
  4. dataCompareR:::matchColumns(dfA, dfB)
  5. dataCompareR:::subsetDataColumns(DFA, DFB, colInfoList)
 14. dplyr::select_(., .dots = colInfoList[["commonCols"]])
 15. dplyr:::lazy_deprec("select", hint = FALSE)

[[2]]
<deprecated>
message: `funs()` is deprecated as of dplyr 0.8.0.
Please use a list of either functions or lambdas: 

  # Simple named list: 
  list(mean = mean, median = median)

  # Auto named with `tibble::lst()`: 
  tibble::lst(mean, median)

  # Using lambdas
  list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
backtrace:
 1. dataCompareR::rCompare(...)
 2. dataCompareR:::processFlow(...)
 3. dataCompareR:::compareData(...)
 4. dataCompareR:::locateMismatches(DFA, DFB, keys, maxMismatches)
 9. dplyr::funs(is.na)`

**Comment by KrishanBhasin** [comment]
>Out of curiosity what's the 'PR' mean in your mention to Ben1787?
>Open to others creating a pull request and attempting to resolve (if I get time one weekend)?

Yep, sorry for the use of an acronym.

If you or anyone else was open to contributing a Pull Request addressing the warnings, it would be warmly welcomed by the project.

**Comment by sclewis23** [comment]
created pull request #117
