### ISSUE TITLE
Incorrectly flagging indices with duplicate values

### ISSUE THREAD

**Issue by ben1787** [capitalone/dataCompareR#95]
See the simple example below:

<img width="423" alt="Capture" src="https://user-images.githubusercontent.com/4843501/88730345-deb91500-d103-11ea-8997-25737d343b5e.PNG">

**Comment by sajohnston** [comment]
Thank you for raising this and apologies for the inconvenience. I will look into resolving this in the next few days.

**Comment by rnobleeddy** [comment]
If it helps I can vaguely remember that multiple keys are handled by merging the indexes together at https://github.com/capitalone/dataCompareR/blob/ee09a1d10415d70cdeb7a76607c0f23bb573fe34/dataCompareR/R/pd_matchRows.R#L143

This probably isn't the prettiest way of handling multiple keys but I imagine there was a good reason! I'd guess changing

```
df_a$dataCompareR_merged_indices <- do.call(paste,c(df_a[indices],sep = ""))
`df_b$dataCompareR_merged_indices <- do.call(paste,c(df_b[indices],sep = ""))
```

to

```
df_a$dataCompareR_merged_indices <- do.call(paste,c(df_a[indices],sep = "_"))
`df_b$dataCompareR_merged_indices <- do.call(paste,c(df_b[indices],sep = "_"))
``` 

Would fix it. I don't have R setup on this PC but if I get a chance I'll try to make a PR.

**Comment by sajohnston** [comment]
Thanks @rnobleeddy ! I'll make that change this afternoon.

**Comment by sajohnston** [comment]
Sorry, I forgot to make a response to this! This change is on the Dev branch, so you can install from there. We'll be merging it into master shortly.
